# Replacements are string substitutions using
# https://nitely.github.io/nim-regex/regex.html#replace%2Cstring%2CRegex%2Cstring%2Cint
# They run on each snippet in the order defined, before the snippet is
# added to the CHANGELOG.md file.
# For example, uncomment the following lines to replace issue numbers with
# links to your GitHub project.

[[replacement]]
pattern = '#(\d+)'
replace = "[#$1](https://github.com/iffy/nim-argparse/issues/$1)"
